project_id = "cwigkiplwauyiyogegtj"

[functions.yoco-webhook]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true

[functions.add-staff-member]
verify_jwt = true

[functions.remove-staff-member]
verify_jwt = true